### ISSUE TITLE
Explain why openssh and windows updates are mutually exclusive

### ISSUE THREAD

**Issue by lonniev** [joefitzgerald/packer-windows#127]
Some of us want an updated Windows image WITH openssh installed. Why does Autounattend.xml place its commenting so that one gets one or the other but not both?

If there's an incompatibility here, then document it.

**Comment by icnocop** [comment]
There is a discrepancy (which adds to the confusion) with the autounattend.xml files between windows 7 and windows 2012 r2 for example.

In the Windows 7 Autounattend.xml file, the "" section disables windows updates, but that section in some of the other Autounattend.xml files do not.

I also think that openssh should be installed regardless of windows updates so that packer can actually connect to the vm as part of its build process because packer doesn't support WinRM yet.

Thank you.

**Comment by sneal** [comment]
#200 addresses this issue
